export const folders = {
    exe: "Ejecutables",
    txt: "Archivos de texto",
    pdf: "Documentos PDF",
    epub: "Libros",
    jpg: "Imagenes",
    jpeg: "Imagenes",
    png: "Imagenes",
    raw: "Imagenes",
    mp3: "Musica",
    mp4: "Videos",
    mkv: "Videos",
    xlsx: "Documentos Excel",
    gsheet: "Documentos Excel",
    csv: "Documentos Excel",
    gdoc: "Documentos Word",
    doc: "Documentos Word",
    docx: "Documentos Word",
    ppt: "Presentaciones",
    pptx: "Presentaciones",
    rar: "Archivos comprimidos",
    zip: "Archivos comprimidos",
    cpp: "Programacion",
    cp: "Programacion",
    js: "Programacion",
    ts: "Programacion",
    jsx: "Programacion",
    tsx: "Programacion",
    drawio: "Diagramas",
    vsdx: "Diagramas",
    sql: "Bases de datos"
}
